import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

// Sample vehicles for demo/development when database table doesn't exist yet
const SAMPLE_VEHICLES = [
  {
    id: '1',
    host_id: 'demo-host-1',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    category: 'car',
    daily_rate: 89,
    description: 'Electric luxury with autopilot. Perfect for road trips to Lake Tahoe. This Tesla Model 3 Long Range comes with full self-driving capability, premium interior, and an incredible sound system. Range of 350+ miles means no range anxiety for your Tahoe adventures.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1562911791-c7a97b729ec5?w=800&auto=format&fit=crop',
    ],
    is_awd: false,
    has_ski_rack: false,
    has_tow_hitch: false,
    seats: 5,
    fuel_type: 'electric',
    transmission: 'automatic',
    instant_book: true,
    rating: 4.9,
    trip_count: 47,
    host_name: 'Michael R.',
    host_avatar: null,
    host_member_since: '2022',
    host_response_rate: 98,
    host_response_time: 'Within an hour',
  },
  {
    id: '2',
    host_id: 'demo-host-2',
    make: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2023,
    category: 'suv',
    daily_rate: 125,
    description: 'Ultimate off-road capability. Ski rack included for winter adventures. This Rubicon is fully loaded with leather seats, heated steering wheel, and the cold weather package. Take the top off in summer or hit the trails year-round.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1506015391gy7f6fd-86eab?w=800&auto=format&fit=crop',
    ],
    is_awd: true,
    has_ski_rack: true,
    has_tow_hitch: true,
    seats: 4,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: true,
    rating: 4.8,
    trip_count: 62,
    host_name: 'Sarah K.',
    host_avatar: null,
    host_member_since: '2021',
    host_response_rate: 100,
    host_response_time: 'Within minutes',
  },
  {
    id: '3',
    host_id: 'demo-host-3',
    make: 'Ford',
    model: 'F-150 Raptor',
    year: 2024,
    category: 'truck',
    daily_rate: 175,
    description: 'Desert beast with tow package. Ready for any terrain. The Raptor features Fox Racing shocks, 37-inch tires, and 450hp twin-turbo V6. Perfect for desert adventures or towing your toys to the lake.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1590739225287-bd31519780c3?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1590739225287-bd31519780c3?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    ],
    is_awd: true,
    has_ski_rack: true,
    has_tow_hitch: true,
    seats: 5,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: true,
    rating: 5.0,
    trip_count: 23,
    host_name: 'Jake T.',
    host_avatar: null,
    host_member_since: '2023',
    host_response_rate: 95,
    host_response_time: 'Within an hour',
  },
  {
    id: '4',
    host_id: 'demo-host-4',
    make: 'BMW',
    model: 'X5 M',
    year: 2023,
    category: 'suv',
    daily_rate: 145,
    description: 'Luxury meets performance. AWD with premium ski rack. The X5 M Competition delivers 617hp and incredible handling. Heated and cooled seats, panoramic roof, and premium Harman Kardon audio.',
    location_city: 'Sparks',
    location_state: 'NV',
    location_lat: 39.5349,
    location_lng: -119.7527,
    thumbnail: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop',
    ],
    is_awd: true,
    has_ski_rack: true,
    has_tow_hitch: false,
    seats: 5,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: true,
    rating: 4.7,
    trip_count: 35,
    host_name: 'Lisa M.',
    host_avatar: null,
    host_member_since: '2022',
    host_response_rate: 92,
    host_response_time: 'Within a few hours',
  },
  {
    id: '5',
    host_id: 'demo-host-5',
    make: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    category: 'car',
    daily_rate: 299,
    description: 'Iconic sports car. Weekend special available. Experience the legendary 911 with 379hp flat-six engine, PDK transmission, and Sport Chrono package. Perfect for a memorable drive around Lake Tahoe.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format&fit=crop',
    ],
    is_awd: false,
    has_ski_rack: false,
    has_tow_hitch: false,
    seats: 2,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: true,
    rating: 5.0,
    trip_count: 12,
    host_name: 'David W.',
    host_avatar: null,
    host_member_since: '2023',
    host_response_rate: 100,
    host_response_time: 'Within minutes',
  },
  {
    id: '6',
    host_id: 'demo-host-6',
    make: 'Toyota',
    model: '4Runner TRD Pro',
    year: 2024,
    category: 'suv',
    daily_rate: 115,
    description: 'Trail-ready with rooftop tent compatibility. Perfect for camping. The TRD Pro features KDSS suspension, crawl control, and multi-terrain select. Roof rack included for all your gear.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1625231334168-32a5765e7a8e?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1625231334168-32a5765e7a8e?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop',
    ],
    is_awd: true,
    has_ski_rack: true,
    has_tow_hitch: true,
    seats: 5,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: true,
    rating: 4.9,
    trip_count: 89,
    host_name: 'Amanda C.',
    host_avatar: null,
    host_member_since: '2020',
    host_response_rate: 99,
    host_response_time: 'Within an hour',
  },
  {
    id: '7',
    host_id: 'demo-host-7',
    make: 'Winnebago',
    model: 'Travato',
    year: 2023,
    category: 'rv',
    daily_rate: 225,
    description: 'Compact Class B RV. Sleep 2, full kitchen, perfect for Tahoe camping. This Travato features a murphy bed, wet bath, and full galley with refrigerator, microwave, and two-burner stove. Solar panels and lithium batteries for off-grid camping.',
    location_city: 'Reno',
    location_state: 'NV',
    location_lat: 39.5296,
    location_lng: -119.8138,
    thumbnail: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop',
    ],
    is_awd: false,
    has_ski_rack: false,
    has_tow_hitch: false,
    seats: 2,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: false,
    rating: 4.8,
    trip_count: 18,
    host_name: 'Tom B.',
    host_avatar: null,
    host_member_since: '2022',
    host_response_rate: 88,
    host_response_time: 'Within a few hours',
  },
  {
    id: '8',
    host_id: 'demo-host-8',
    make: 'Polaris',
    model: 'RZR Pro XP',
    year: 2024,
    category: 'atv',
    daily_rate: 350,
    description: 'Ultimate desert toy. Helmet and trailer included. The RZR Pro XP features 181hp turbocharged engine, 32 inches of suspension travel, and 64-inch width for stability. Trailer included for transport to your favorite riding area.',
    location_city: 'Sparks',
    location_state: 'NV',
    location_lat: 39.5349,
    location_lng: -119.7527,
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop',
    ],
    is_awd: true,
    has_ski_rack: false,
    has_tow_hitch: false,
    seats: 2,
    fuel_type: 'gasoline',
    transmission: 'automatic',
    instant_book: false,
    rating: 5.0,
    trip_count: 8,
    host_name: 'Chris P.',
    host_avatar: null,
    host_member_since: '2024',
    host_response_rate: 100,
    host_response_time: 'Within minutes',
  },
]

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const supabase = await createClient()

  // Try to fetch from database first
  const { data, error } = await supabase
    .from('active_listings')
    .select('*')
    .eq('id', id)
    .single()

  // If database query fails, use sample data
  if (error) {
    console.error('Error fetching vehicle:', error)
    
    const sampleVehicle = SAMPLE_VEHICLES.find(v => v.id === id)
    
    if (!sampleVehicle) {
      return NextResponse.json({ error: 'Vehicle not found' }, { status: 404 })
    }
    
    return NextResponse.json(sampleVehicle)
  }

  if (!data) {
    return NextResponse.json({ error: 'Vehicle not found' }, { status: 404 })
  }

  return NextResponse.json(data)
}
