import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { headers } from 'next/headers'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// Runs weekly on Monday at 7am to generate market report
export async function GET(request: NextRequest) {
  // Verify cron secret
  const headersList = await headers()
  const authHeader = headersList.get('authorization')
  
  if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const startTime = Date.now()

  try {
    const host = request.headers.get('host') || 'localhost:3000'
    const protocol = host.includes('localhost') ? 'http' : 'https'

    // Run market analysis for each category
    const categories = ['car', 'suv', 'truck', 'rv', 'atv']
    const results: Record<string, any> = {}

    for (const category of categories) {
      try {
        const response = await fetch(`${protocol}://${host}/api/agents/market-intelligence`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            analysis_type: 'weekly_report',
            vehicle_category: category 
          }),
        })

        if (response.ok) {
          results[category] = await response.json()
        }
      } catch (err) {
        console.error(`Failed to analyze ${category}:`, err)
        results[category] = { error: String(err) }
      }

      // Rate limit
      await new Promise(resolve => setTimeout(resolve, 2000))
    }

    // Send weekly summary email
    if (process.env.SENDGRID_API_KEY) {
      await sendWeeklyMarketReport(results)
    }

    return NextResponse.json({
      success: true,
      categories_analyzed: Object.keys(results).length,
      results,
      processing_time_ms: Date.now() - startTime,
    })

  } catch (error) {
    console.error('Market intelligence cron error:', error)
    return NextResponse.json({ error: 'Cron job failed' }, { status: 500 })
  }
}

async function sendWeeklyMarketReport(results: Record<string, any>) {
  if (!process.env.SENDGRID_API_KEY) return

  const sgMail = await import('@sendgrid/mail')
  sgMail.default.setApiKey(process.env.SENDGRID_API_KEY)

  // Build HTML report
  let categorySections = ''
  for (const [category, data] of Object.entries(results)) {
    if (data.analysis) {
      categorySections += `
        <h3>${category.toUpperCase()}</h3>
        <p><strong>Demand Forecast:</strong> ${data.analysis.demand_forecast}</p>
        <p><strong>Rate Adjustment:</strong> ${data.analysis.recommended_rate_adjustment > 0 ? '+' : ''}${data.analysis.recommended_rate_adjustment}%</p>
        <p><strong>Summary:</strong> ${data.analysis.market_summary}</p>
        <p><strong>Opportunities:</strong></p>
        <ul>${data.analysis.top_opportunities?.map((o: string) => `<li>${o}</li>`).join('') || '<li>None identified</li>'}</ul>
        <hr>
      `
    }
  }

  await sgMail.default.send({
    to: 'joe@rentanddrive.net',
    from: process.env.SENDGRID_FROM_EMAIL || 'reports@rentanddrive.net',
    subject: `Weekly Market Report - Rent and Drive - ${new Date().toLocaleDateString()}`,
    html: `
      <h1>Weekly Market Intelligence Report</h1>
      <p>Generated: ${new Date().toLocaleString()}</p>
      <hr>
      ${categorySections}
      <p style="color: #666; font-size: 12px;">
        This report was generated by the R&D Market Intelligence Agent.
        <a href="https://rentanddrive.net/dashboard/agents">View Dashboard</a>
      </p>
    `,
  })
}
